language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: F7UoC5o9gixHJDabCFFiK7FIJz2Q1HZIQDq3LtMvRLayxqw9lpbuK4RBuz/m9kZo321YyoQBIb0v+C5P+36jEuXgzmZ87t0uT1/4krksZnH82jeUt0aEugx2h9wk0lxaJDKr5/DmQxYtc63LZmZSWiPXEWgRdR9kdMl8XAWInW8+7AuD6LbAEj6e6b709HwndojTRfgCsMpjVdePh9RPGLEGyC0VMvQVxU3y0v3ujDfEKYq1Ol5lTblpejUIohbvxZ3Qu9ZlnNM2sCXEuJietm0bqy0ViwG1jmtY3bCEhucSHwQY3HhtnJODyim+u25bMehWAziJLT13k4KosvtROT8zetxe/SMmljFJKXLixLgdlFFZqVkIe0lTPuNLXxuxL55we0gSXTo76b3sGuZDEr3QDPVSlrn3jRFuO5JwQPh+bsevbtqXhXoPAkQF4kMp1s3gMor6HPt6hyI6NvnbHTuMJJPgFDHxJZaesdj39nuoO4w/KjGxSsibMk+hXTYGWEm04ftbyLcHKFfG8lD/BZQi/unDP1/HwyIXII6imfwn+hFYb+HYlgVS58GWIrELAeksKkj+PDXKMu2g6mb87gVUCHfyLP5yneQ1UtmhhA4KWGz+SS7SfVbMeODrOui3z4WPK4BoIdajaK8tyHvaqivZzoJxxcNnJGYGNxY22io=
  app: secure-beach-90974
  on:
    repo: xxsenix/responsibillity
